vlib/v/checker/tests/result_type_call_err.vv:12:2: error: new_foo() returns a Result, so it should have either an `or {}` block, or `!` at the end
   10 | 
   11 | fn main() {
   12 |     new_foo().foo()
      |     ~~~~~~~~~
   13 | }
